### PR TITLE
Feature/img bug

### LINKED ISSUE #38: On Page refresh country image is breaking QuizPage and Form component
- [ ]  Need grab local storage data on page refresh and assign into img src, need condition to render it correctly and make it persist on page refresh

### PR DESCRIPTION
**Pull request by Fakhatova**
# Thank you for pushing your code!
## What (if any) features are you implementing?
- I did work on small bug, which is on page refresh image would break

## What (if anything) did you refactor?
- just refactored quizPage components img element to render consitionally, also fixed indentations around files 

## Were there any issues that arose?
-

## Is there anything that you need from your teammate?
-

## Any other comments, questions, or concerns?
-

## Type of change
- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)

## How Has This Been Tested?
- [ ] open index.html
- [ ] console.log()
- [ ] dev tools

## Checklist:
- [ ] My code follows the style guidelines of this project
- [ ] I have performed a self-review of my own code
- [ ] I have commented my code, particularly in hard-to-understand areas

 closes #38

### CODE REVIEW

File: src/components/Answers/Answers.tsx [hunk 1]
```diff
@@ -21,12 +21,14 @@ interface Iprops{
...
-
-  const [answer, setAnswer] = useState<string | number>('')
-  const [currency] = currentCountry.currencies
-  const [languages, setLanguage] = useState<string[]>()
+const Answers: React.FC<IAnswerProps> = ({ currentCountry, questions, guess }) => {
+  const [answer, setAnswer] = useState<string | number>('');
+  const [currency] = currentCountry.currencies;
+  const [languages, setLanguage] = useState<string[]>();
 
+   // *******************************************************
```
Comment (maeduphorne) [inline src/components/Answers/Answers.tsx:29]: Love the additions of the labels to explain the functionality. This is a great step in showing developer empathy!

File: src/components/QuizPage/QuizPage.tsx [hunk 2]
```diff
@@ -20,42 +20,54 @@ interface IQuizPageProps {
...
-  
   return (
     <div className="display-area quiz-display" >
       <section className="display-area" >
         {currentCountry && (
         <div className="quiz-contents">
-          <img src={currentCountry.flag} alt={`${currentCountry.name} flag`} className="flag-img" />
-         {country  && <h2>{questions}?</h2>}
-        {country  && <Form questions={`${questions} ${country.name}?`} currentCountry={country}/>}  
+          {country &&
```
Comment (maeduphorne) [inline src/components/QuizPage/QuizPage.tsx:58]: Good call adding the conditional to keep the flag displayed. A great catch to make the app less buggy
